version: '3.7'

services:
  mongo:
    image: ${MONGO_IMAGE}
    restart: always
    expose:
      - "${MONGO_PORT}"
    ports:
      - "127.0.0.1:${MONGO_PORT}:${MONGO_PORT}"
    volumes:
      - "${MONGO_VOLUME}:/data/db:z"
    container_name: hacchui-mongo
  nginx:
    image: ${NGINX_IMAGE}
    depends_on:
      - hacchui
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/nginx:/etc/nginx/conf.d:z
      - ./data/certbot/conf:/etc/letsencrypt:z
      - ./data/certbot/www:/var/www/certbot:z
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & envsubst < /etc/nginx/conf.d/app.conf.template > /etc/nginx/conf.d/app.conf && nginx -g \"daemon off;\"'"
    environment:
      - NGINX_SERVER_NAME
      - NGINX_HACCHUI_PORT=${HACCHUI_PORT}
      - DOLLAR=$$
  certbot:
    image: ${CERTBOT_IMAGE}
    depends_on:
      - nginx
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt:z
      - ./data/certbot/www:/var/www/certbot:z
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  hacchui:
    image: ${HACCHUI_IMAGE}
    depends_on:
      - mongo
    restart: always
    ports:
      - "${HACCHUI_PORT}:${HACCHUI_PORT}"
      - "${SLACKBOT_PORT}:${SLACKBOT_PORT}"
    environment:
      - MONGO_URL=mongodb://${MONGO_HOST}:${MONGO_PORT}/${MONGO_DB}
      - ROOT_URL=https://${NGINX_SERVER_NAME}
      - PORT=${HACCHUI_PORT}
      - METEOR_SETTINGS
